### ISSUE TITLE
Images in posts do not work without uggifying link

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#1]
Images only appear when I add a bunch of "look one folder beneath" formatting, ie "../../../../".

![screen shot 2015-12-01 at 12 18 50 pm](https://cloud.githubusercontent.com/assets/3204193/11516164/d24f1dda-9825-11e5-9f22-22d5395a9347.png)

**Comment by figureone** [comment]
http://stackoverflow.com/questions/25295418/jekyll-declare-image-path-in-front-matter-as-variable-using-site-url

**Comment by billymeinke** [comment]
Thanks @figureone!
