### ISSUE TITLE
Set up "Subscribe via email" for new articles

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#11]
Make it easy for COE faculty to sign up to be alerted via email when new articles are posted. Can use a third-party tool (ie Mailchimp) or link to other COE/DCDC mailing list.

**Comment by enriquezm** [comment]
http://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website

**Comment by billymeinke** [comment]
Low priority right now, closing this for the moment
