### ISSUE TITLE
Change site URL to flow.coe.hawaii.edu

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#12]
Currently lives at https://flow.coe.hawaii.edu/flow/

**Comment by billymeinke** [comment]
Also get rid of the old WP site

**Comment by enriquezm** [comment]
Working on getting this done with Paul now.

**Comment by enriquezm** [comment]
alright Paul was able to give the site its final home: https://flow.coe.hawaii.edu/

**Comment by billymeinke** [comment]
Thanks @enriquezm @figureone !
