### ISSUE TITLE
Clean out tags and make sure they have the correct spelling

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#14]
Tag A spelled as 'Assessment'
![Tag with 'Assessment'](https://cloud.githubusercontent.com/assets/12424864/12460867/0c7793b0-bf5a-11e5-8b4f-537826f6d350.png)

Tag B spelled as 'Assessments' (plural)
![Tag with 'Assessments'](https://cloud.githubusercontent.com/assets/12424864/12460868/0c922946-bf5a-11e5-9c58-b2f6fc217f3c.png)

**Comment by billymeinke** [comment]
@fjumawan Could you take a look at this? May need to scan existing posts to correct misspelled tags.

**Comment by enriquezm** [comment]
@fjumawan @billymeinke tags have been "cleaned" out.
