### ISSUE TITLE
Clean and remove redundant tutorial posts.

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#15]
Mostly left over from running tests on the site, but need to clean out any duplicates.

![screen shot 2016-01-20 at 9 45 12 am](https://cloud.githubusercontent.com/assets/12424864/12460965/84d11336-bf5a-11e5-8941-deb6b242ca19.png)

**Comment by billymeinke** [comment]
@fjumawan Would you be able to handle this? Be sure to delete the post _and_ the folder of images for the post. Let me or @enriquezm know if you need a hand!
