### ISSUE TITLE
Add commenting capabilities for each post (disqus)

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#16]

**Comment by enriquezm** [comment]
@billymeinke did we still want to add commenting? If we do, what disqus account should we use?

**Comment by billymeinke** [comment]
I think we can get away without including comments for now. Can be
introduced later as long as it doesn't break the post layout, ya?

On Thu, Jan 21, 2016 at 3:11 PM, Myles Enriquez notifications@github.com
wrote:

> @billymeinke https://github.com/billymeinke did we still want to add
> commenting? If we do, what disqus account should we use?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/flow/issues/16#issuecomment-173768016.

## 

Billy Meinke, MEd
@billymeinke https://twitter.com/billymeinke / Web
http://billymeinke.github.io

**Comment by enriquezm** [comment]
@billymeinke alright, I have it working in a branch (disqus branch) so whenever we're ready for them I'll just merge it with master.

**Comment by billymeinke** [comment]
Need to attach Disqus account to TDP gmail and use that widget instead of Myles'

**Comment by billymeinke** [comment]
@enriquezm I PMed you the Disqus code for the account, go ahead and merge your branch and include our widget

**Comment by billymeinke** [comment]
And we have comments!
