### ISSUE TITLE
Be able to filter posts by category in sidebar

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#17]
Small bug that needs to be fixed, nothing major.

**Comment by enriquezm** [comment]
![screen shot 2016-01-22 at 9 26 15 am](https://cloud.githubusercontent.com/assets/12424864/12520702/3451ad62-c0ea-11e5-969c-508dd22635a0.png)

Afterclicking **how-to_** in side bar, shows empty list

**Comment by billymeinke** [comment]
@enriquezm Any idea what's breaking this?

**Comment by enriquezm** [comment]
@billymeinke I've been trying to figure it out, but because it's working on my local copy and not the live server, I'm stumped. 

Could you try pulling and running it on your local machine when you get a chance? To see if it's just my machine or the live server that's not working?

I've also cleaned out all 'dummy posts' in our site so the category side bar will only list one category for now, since we don't currently have any posts under **Troubleshooting** or **Strategies**.

**Comment by enriquezm** [comment]
Bug fixed. Not sure exactly what the fix was because I tried multiple things at once. 

I did log into the live server and noticed that _site/how-to/index.html was not the same as the generated file on my local instance. So I manually built the file on the live server and that seemed to fix the issue. Almost like it needed a force rebuild.
