### ISSUE TITLE
Tabs do not collapse on click, after being opened.

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#23]
![screen shot 2016-02-04 at 3 29 01 pm](https://cloud.githubusercontent.com/assets/12424864/12835417/0cfc8114-cb54-11e5-8907-4049a6b46ecc.png)
Cannot close on category page: https://flow.coe.hawaii.edu/how-to/

**Comment by enriquezm** [comment]
Issue Resolved:

#### Problem:
- Tabs not collapsing on click only on category template (category.html)

#### Fixed by:
- Removing extra script added to category template (2 of the same scripts being called)

#### View Page:
- https://flow.coe.hawaii.edu/how-to/

**Comment by billymeinke** [comment]
Thanks @enriquezm!
