### ISSUE TITLE
Clicking on category twice will produce search results

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#24]

**Comment by enriquezm** [comment]
Issue resolved by @parkjc 

https://flow.coe.hawaii.edu/tag/COE%20Website/

### Problem was:
- Clicking on a post's category link from a tag listing page was causing a "no search results" bug.

### How it was fixed:
- tag_index.html was still searching categories that had capital letters
- had to downcase the category portion in the tags file
