### ISSUE TITLE
Improve "Tip" font face to be more friendly

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#27]
Currently is plainly styled as "code", should be more friendly

**Comment by billymeinke** [comment]
Let's create a new CSS class without modifying the code class.

**Comment by billymeinke** [comment]
Bump

**Comment by enriquezm** [comment]
Resolved. Tips are now styled without using a <code> tag. 

![screen shot 2016-02-17 at 5 08 18 pm](https://cloud.githubusercontent.com/assets/12424864/13132688/169d4330-d599-11e5-8c0c-c687ab886e08.png)

No ticks (``) needed anymore. Just need the word "tip" and it should be styled now. It's also not case-sensitive, so don't worry about upper case or lower case.

[View Live Site Example](https://assist.coe.hawaii.edu/how-to/2016/01/22/view-files-shared-to-you-on-owncloud.html)

**Comment by enriquezm** [comment]
@billymeinke going to close this seeing that it's similar to issue #56
