### ISSUE TITLE
Fix strange spacing in ordered instruction lists

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#28]
![screenshot 2016-02-10 10 45 28](https://cloud.githubusercontent.com/assets/3204193/12961243/7e1a4064-cfe3-11e5-9a7b-63c4e5440373.png)

**Comment by enriquezm** [comment]
Issue resolved:

![screen shot 2016-02-11 at 12 35 54 pm](https://cloud.githubusercontent.com/assets/12424864/12993050/0f62b24e-d0bc-11e5-8b6c-debee4d327d6.png)

[example on live site](https://flow.coe.hawaii.edu/how-to/2016/02/01/set-up-grade-book-tool-in-laulima.html)

**Comment by billymeinke** [comment]
Awesome, thanks!

On Thu, Feb 11, 2016 at 12:37 PM, Myles Enriquez notifications@github.com
wrote:

> Issue resolved:
> 
> [image: screen shot 2016-02-11 at 12 35 54 pm]
> https://cloud.githubusercontent.com/assets/12424864/12993050/0f62b24e-d0bc-11e5-8b6c-debee4d327d6.png
> 
> (example on live site)[
> https://flow.coe.hawaii.edu/how-to/2016/02/01/set-up-grade-book-tool-in-laulima.html
> ]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/flow/issues/28#issuecomment-183087667.

## 

Billy Meinke, MEd
@billymeinke https://twitter.com/billymeinke / Web
http://billymeinke.github.io
