### ISSUE TITLE
Add Gitbook documentation link to README file

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#3]
We should link to the documentation, or somehow display it on a page.

**Comment by enriquezm** [comment]
Added gitbook documentation link to README.md: https://github.com/uhm-coe/flow#flow

**Comment by billymeinke** [comment]
@enriquezm Looks like a good start on the documentation. Can @fjumawan lend a hand completing the other few how-to pages? https://www.gitbook.com/book/enriquezm/flow-support-site-documentation/details

**Comment by enriquezm** [comment]
Yeah of course! @fjumawan I sent you an invite to add you as a collaborator for the flow documentation on gitbook. @billymeinke @parkjc let me know if you guys want an invite as well.

**Comment by ghost** [comment]
Thanks @enriquezm!

**Comment by billymeinke** [comment]
Yes, please add me as a collaborator! Many thanks.

On Fri, Jan 22, 2016 at 12:53 PM, Frank Jumawan notifications@github.com
wrote:

> Thanks @enriquezm https://github.com/enriquezm!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/flow/issues/3#issuecomment-174080090.

## 

Billy Meinke, MEd
@billymeinke https://twitter.com/billymeinke / Web
http://billymeinke.github.io

**Comment by enriquezm** [comment]
@billymeinke alright added you as well

**Comment by billymeinke** [comment]
@enriquezm Can you add my billymeinke username? Or my Gmail account? Not using Gitbook on hawaii.edu

**Comment by enriquezm** [comment]
@billymeinke Alright, you should be good to go.
