### ISSUE TITLE
Transfer Google Analytics to TDP email

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#31]
Transfer ownership or install GA from TDP gmail account

**Comment by ghost** [comment]
Created a tracking id for tdpcoe@gmail.com to track and sent link for Myles to embed into site.

**Comment by enriquezm** [comment]
@fjumawan google analytics is now set for tdpcoe@gmail.com on live site.

**Comment by billymeinke** [comment]
Awesome. Thanks @fjumawan + @enriquezm!
