### ISSUE TITLE
Move site to assist.coe.hawaii.edu

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#32]
from flow.coe.hawaii.edu

**Comment by billymeinke** [comment]
@figureone did this happen to go through? Thanks!

**Comment by figureone** [comment]
it did, but the web server conf was overwritten, so @parkjc is working on reapplying.

**Comment by billymeinke** [comment]
Ah yes, thanks for the update. Let's also make sure the site is publicly viewable @parkjc

**Comment by parkjc** [comment]
flow is now being redirected to assist and is publicly available.

**Comment by billymeinke** [comment]
thanks @parkjc!
