### ISSUE TITLE
Need to change href on search results page.

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#34]
![screen shot 2016-02-22 at 10 54 24 am](https://cloud.githubusercontent.com/assets/12424864/13232293/af1ada02-d952-11e5-90fa-c4b85fa8f126.png)
Need to change from upper to lower case slug

**Comment by parkjc** [comment]
fixed

**Comment by enriquezm** [comment]
Thanks @parkjc! I guess all categories needed the fix, so I did that as well.
