### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#37]
assist.coe.hawaii.edu does not currently redirect to https://assist.coe.hawaii.edu/

**Comment by pkarjala** [comment]
FYI, tested this in each of the following scenarios:

Hard-wire connected to COE Network.
Connected to University WiFi.
Connected to University WiFi while on VPN.

The redirect does currently appear to functional at this time.

We can check the server logs to see if there's anything going on there.

**Comment by parkjc** [comment]
Was able to reproduce this problem:
- clear cache of browser, reopen a private window (so it doesnt save the cache) and go to either assist.coe.hawaii.edu or flow.coe.hawaii.edu. It'll give a can't connect to server error.

**Reason:**
- In the nginx config file i had this line: `listen [::]:80 ipv6only=on`
- According to the nginx docs, post 1.3.4 (we're on version 1.4.6) ipv6only=on sets the socket to listen only on IPv6 connections (http://nginx.org/en/docs/http/ngx_http_core_module.html), at least that was how i interpreted it. Heres the excerpt: 

ipv6only=on|off
this parameter (0.7.42) determines (via the IPV6_V6ONLY socket option) whether an IPv6 socket listening on a wildcard address [::] will accept only IPv6 connections or both IPv6 and IPv4 connections. This parameter is turned on by default. It can only be set once on start.
Prior to version 1.3.4, if this parameter was omitted then the operating system’s settings were in effect for the socket.

**Fix:**
- set ipv6only=off (at least until we have ipv6 support?)

**Comment by pkarjala** [comment]
I think it would be best to continue to support IPv4 for the foreseeable future.

**Comment by enriquezm** [comment]
@parkjc can we confirm that this has been resolved?

**Comment by parkjc** [comment]
@mylesenri yes, just tested on a newly reimaged machine that has never logged into assist before (probably overkill) and it redirects ok.

**Comment by enriquezm** [comment]
@parkjc alright thanks!
