### ISSUE TITLE
Update header image

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#38]
Let's borrow another one from unsplash, maybe without an iPod reference.

**Comment by windfix** [comment]
+1  ;)

**Comment by enriquezm** [comment]
@billymeinke Alright sounds good! Did you have any you wanted in particular? I only picked the current one because it followed our color scheme.

**Comment by billymeinke** [comment]
@enriquezm nope, no preference. I like the idea of showing a desk, something similar to what the site visitors will have in front of them (assuming they are trying to figure out something on their computer).

There are some more good ones here: https://unsplash.com/search?utf8=%E2%9C%93&keyword=desk&button=

Can also take an image that doesn't necessarily fit with the color scheme and adjust the colors/levels to work.

**Comment by enriquezm** [comment]
@billymeinke I'll look into it and pick the best 3 and show you.

**Comment by enriquezm** [comment]
Hey @billymeinke found some header images that might work for the Assist site on unsplash:

![download1](https://cloud.githubusercontent.com/assets/12424864/13797418/86f7bcdc-eab1-11e5-8ca8-e4d60259af04.jpg)
![download2](https://cloud.githubusercontent.com/assets/12424864/13797419/8711eabc-eab1-11e5-9bbc-b280b634026b.jpg)
![download3](https://cloud.githubusercontent.com/assets/12424864/13797421/873799e2-eab1-11e5-8038-b77507fc9f46.jpg)

Let me know if you don't like these so I can look on other places.

**Comment by billymeinke** [comment]
@enriquezm I prefer number 3 or number 1. Thanks!

**Comment by enriquezm** [comment]
@billymeinke alrigth I'll go with number 3, thanks!

**Comment by ghost** [comment]
@billymeinke @enriquezm +1 for no. 3
