### ISSUE TITLE
Allow users to view all posts with the same tag

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#4]
I want to be able to click on an article tag and see all other posts that share that same tag.

<img width="683" alt="screen shot 2016-01-13 at 9 10 23 am" src="https://cloud.githubusercontent.com/assets/3204193/12304814/99c75532-b9d5-11e5-83a6-f8a249c6ffb8.png">

**Comment by enriquezm** [comment]
You are now able to click on an article tag and see all other posts that share that same tag.

**Comment by enriquezm** [comment]
Alright @billymeinke you can now click on an article tag and see all other posts that share the same tag on the live site: https://flow.coe.hawaii.edu/

**Comment by billymeinke** [comment]
Looks good, thanks Myles.

On Wed, Jan 20, 2016 at 9:46 AM, Myles Enriquez notifications@github.com
wrote:

> Alright @billymeinke https://github.com/billymeinke you can now click
> on an article tag and see all other posts that share the same tag on the
> live site: https://flow.coe.hawaii.edu/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/flow/issues/4#issuecomment-173337952.

## 

Billy Meinke, MEd
@billymeinke https://twitter.com/billymeinke / Web
http://billymeinke.github.io
