### ISSUE TITLE
Arbitrary URLs do not fail nicely to 404 pages

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#40]
Visit a page such as https://assist.coe.hawaii.edu/how-to/2016/01/22/sync-owncloud-files-selectively-to-your-hard-drive.html then remove the info after the trailing slash and hit enter.

https://assist.coe.hawaii.edu/how-to/2016/01/22/ will return an NGINX error page, which is not terribly good looking. Should fail to a nice 404 page instead.

**Comment by parkjc** [comment]
done. redirected 403 forbidden errors to our custom 404 page.
