### ISSUE TITLE
Tip Styling different?

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#43]
Not sure if this is a bug or not, but observing https://assist.coe.hawaii.edu/how-to/2016/01/12/create-a-random-draw-assessment.html, the text for one tip is a very narrow font in red, where another tip is in a nicer font in Green. See screenshot.

![screen shot 2016-03-02 at 3 32 26 pm](https://cloud.githubusercontent.com/assets/12424864/13482848/a2727f74-e093-11e5-8700-6a7c65f0844e.png)

**Comment by enriquezm** [comment]
@fjumawan could I leave this up to you to change all tips to a regular "Tip" instead of using the ticks?

**Comment by ghost** [comment]
@enriquezm no problems, I'll look through all the posts and remove the tick marks.

**Comment by enriquezm** [comment]
@fjumawan Thanks!

**Comment by ghost** [comment]
No problems @enriquezm!
