### ISSUE TITLE
Have footer links open in separate tab or window

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#48]
You may wish to consider opening footer links to external resources (CIS, ITS, Laulima Assistance, etc) in a separate tab or window.

**Comment by enriquezm** [comment]
@pkarjala that's odd. All external links in footer should have already been opening up in separate tabs.

**Comment by pkarjala** [comment]
Checking now, all of the footer links look good; I may have been looking at the incorrect links at the time!

**Comment by enriquezm** [comment]
No worries!
