### ISSUE TITLE
Look over typos

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#52]
Set up a process for having one other person read over typos before being posted.

**Comment by enriquezm** [comment]
Hey @fjumawan @billymeinke I'm not sure if you guys wanted to create a process for reviewing posts? Jekyll does support [drafts](https://jekyllrb.com/docs/drafts/), which is really simple. I can set that up for you guys?

**Comment by enriquezm** [comment]
@fjumawan proof reading will be done through google docs and not through the _drafts folder, correct?

**Comment by ghost** [comment]
@enriquezm To get the key people buy into and get involved in contributing posts for Assist, we will be using Google Docs to post drafts while @billymeinke @cchun8 and I will send the posts to Jekyll. Until we get everyone to contribute straight to Jekyll, we probably won't be using the _drafts folder at this time. You can verify with @billymeinke

**Comment by enriquezm** [comment]
@fjumawan alright sounds good, I just wanted to make sure we have a organized process for you guys. And so I can close this issue. I'll verify with @billymeinke first though.

**Comment by billymeinke** [comment]
Yep, thanks for checking @enriquezm. Going to keep drafts in Google docs for now.
