### ISSUE TITLE
Background-size: cover on site-header

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#54]
Consider using background-size: cover on site header.

**Comment by enriquezm** [comment]
Will need to finish #38 first.

**Comment by ghost** [comment]
@parkjc Has this been done? If not, what is the advantage of this enhancement?

**Comment by billymeinke** [comment]
@fjumawan #38 is now closed, so we can look at this. It's basically just specifying that the header image to stretch and/or crop the header image to fit all screen sizes as needed. Can be adjusted in the css. Let me know if you need a hand.

**Comment by ghost** [comment]
@billymeinke Will look into this.

**Comment by ghost** [comment]
@billymeinke looks like this has been done. 
![screen shot 2016-04-07 at 3 27 10 pm](https://cloud.githubusercontent.com/assets/15221414/14371629/4dae278c-fcd5-11e5-9e88-d47ea4074345.png)

**Comment by billymeinke** [comment]
Great, thanks @fjumawan!

**Comment by ghost** [comment]
@billymeinke No problems! Wast trying to figure out how to do it and I bumped into it. :)
