### ISSUE TITLE
Top button and Next Page button overlaps at certain width (around 900px to mobile phone view)

### ISSUE THREAD

**Issue by ghost** [uhm-coe/flow#58]
![screen shot 2016-03-07 at 9 35 16 am](https://cloud.githubusercontent.com/assets/15221414/13581217/e13d2e5c-e449-11e5-8edc-e4635ed7baf3.png)
![screen shot 2016-03-07 at 9 34 55 am](https://cloud.githubusercontent.com/assets/15221414/13581216/e13cdaba-e449-11e5-93f3-37526bf68938.png)

**Comment by enriquezm** [comment]
@fjumawan Changed button color to give it more contrast from 'Next-Page' buttons and also rounded it to give it a more natural button shape for mobile devices.
