### ISSUE TITLE
Connect Disqus so we are notified of comments on posts

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#59]
Disqus is connected to coeisg@h@waii.edu and we aren't getting notifications of new comments on posts. We need to see them!

**Comment by billymeinke** [comment]
Correction: Disqus is currently associated with tdpcoe@gm@il.com.

**Comment by ghost** [comment]
Created a group coe-isg-grp@h@waii.edu, created a filter in tdpcoe@gm@il.com to fwd all disqus notification messages to group. Tested, works!
