### ISSUE TITLE
Cleanup: remove console.log() from results.js

### ISSUE THREAD

**Issue by figureone** [uhm-coe/flow#62]
https://github.com/uhm-coe/assist/blob/master/assets/js/results.js#L11

**Comment by enriquezm** [comment]
Was using gulp's [gulp-strip-debug](https://www.npmjs.com/package/gulp-strip-debug), but reverted back to just manually removing console.logs. 

### Reasoning:

strip-debug did successfully remove console logs but replaced them with void(0)s which didn't really fix the issue of cleaning out our js code.
