### ISSUE TITLE
Disqus "other articles" links direct to 404

### ISSUE THREAD

**Issue by enriquezm** [uhm-coe/flow#65]
Direct to 404 page when clicking on links that Disqus refers (below disqus commenting)

![screen shot 2016-03-11 at 12 55 25 pm](https://cloud.githubusercontent.com/assets/12424864/13717885/ccf3d17a-e788-11e5-8615-42c65c082750.png)

**Comment by enriquezm** [comment]
#Update 
Narrowed it down and it seems that only the link to "Share ownCloud Online Folders via Links" is one of the few that directs to 404. I believe it's because this article doesn't exist anymore but is still saved on disqus. 

![screen shot 2016-03-11 at 1 34 26 pm](https://cloud.githubusercontent.com/assets/12424864/13718480/7624c0ba-e78e-11e5-86cd-0ba2235076ef.png)

**Comment by billymeinke** [comment]
@fjumawan Can you log into Disqus and remove that comment? If the problem is limited to just that post,  that should take care of it.

**Comment by ghost** [comment]
@billymeinke cleared comments in Disqus, but comments still appear.

**Comment by ghost** [comment]
@billymeinke Looks like all the Disqus comments cleared in Assist.

**Comment by billymeinke** [comment]
Awesome, thanks @fjumawan

On Tue, Apr 5, 2016 at 10:25 AM, Frank Jumawan notifications@github.com
wrote:

> Closed #65 https://github.com/uhm-coe/assist/issues/65.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/assist/issues/65#event-615770254

## 

Billy Meinke, MEd
@billymeinke https://twitter.com/billymeinke / Web
http://billymeinke.github.io
