### ISSUE TITLE
Print Issues on Firefox

### ISSUE THREAD

**Issue by ghost** [uhm-coe/flow#69]
Previewed printout for both Chrome and Firefox Browsers. Chrome prints out fine, however Firefox has breaks between headers, step and tip (see screen shots)
![screen shot 2016-03-17 at 1 20 23 pm](https://cloud.githubusercontent.com/assets/15221414/13864245/013247fe-ec44-11e5-968f-0b57e878e0bd.png)
![screen shot 2016-03-17 at 1 20 36 pm](https://cloud.githubusercontent.com/assets/15221414/13864247/01346c0a-ec44-11e5-9f19-0c741e6788a0.png)
![screen shot 2016-03-17 at 1 19 41 pm](https://cloud.githubusercontent.com/assets/15221414/13864246/0133921c-ec44-11e5-9167-2d4f6f15cce0.png)
![screen shot 2016-03-17 at 1 19 54 pm](https://cloud.githubusercontent.com/assets/15221414/13864244/013228f0-ec44-11e5-9e4f-a566635e5564.png)

**Comment by enriquezm** [comment]
@fjumawan thanks for mentioning this! I'll look into it.

**Comment by enriquezm** [comment]
Related to issue #72

**Comment by ghost** [comment]
@parkjc can we meet on this when you have the chance?

**Comment by parkjc** [comment]
@fjumawan sure thing. i can meet today before 1PM or after 3PM

**Comment by ghost** [comment]
Unable to fix Firefox since there is no universal CSS to have all 3 browsers to print perfectly. Added a notification to print through Chrome or Safari.

**Comment by billymeinke** [comment]
Do we know anything more about this @fjumawan @parkjc? Does Firefox ignore the print.css that was created, or do special rules needed to be applied to help it work?

**Comment by parkjc** [comment]
@billymeinke i'll have to do a bit more research on how firefox print preview works, but it doesnt seem like its recognizing the custom css file. Either that or page breaks in firefox are interpreted differently

**Comment by billymeinke** [comment]
Checked in on this, @parkjc is working on it.

May have to do with "media=print/screen"
