### ISSUE TITLE
Make printing articles make sense

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#7]
Reduce size of font to 14pt, make article images/screenshots full-width (since they will not be opening in a modal).

**Comment by billymeinke** [comment]
Looking better. I'm wondering if we can make the images print larger, maybe sit above or below the instructional text.

**Comment by enriquezm** [comment]
Alright didn't realize how easy it actually is to style 'printer' specific documents, but it's just a matter of creating a separate css file.

**Comment by enriquezm** [comment]
@billymeinke Articles are now printer friendly.

**Comment by billymeinke** [comment]
Looks much better. Thanks @enriquezm
