### ISSUE TITLE
Print This Article Does Not Work on Safari 9.0.3

### ISSUE THREAD

**Issue by ghost** [uhm-coe/flow#70]
Pressed the Print This Article button and nothing happens.

**Comment by enriquezm** [comment]
Hey @fjumawan not sure if this is a cache or version issue. I've tried it on Safari 8.0.8 and it worked fine. Could you try holding down **Shift** and **Click** the Refresh button on your browser?

**Comment by ghost** [comment]
Cool, now it works! Thanks @enriquezm!
