### ISSUE TITLE
Tags Not Showing in Search Results

### ISSUE THREAD

**Issue by ghost** [uhm-coe/flow#71]
Tags not showing, only categories. Can the tags be shown as well?
![screen shot 2016-03-18 at 11 33 51 am](https://cloud.githubusercontent.com/assets/15221414/13892726/6d3d38c8-ecfd-11e5-8979-f86d2251ab65.png)
![screen shot 2016-03-18 at 11 33 36 am](https://cloud.githubusercontent.com/assets/15221414/13892727/6d5d593c-ecfd-11e5-8fda-7ab1613e1199.png)

**Comment by enriquezm** [comment]
@fjumawan I forgot all about this! Working on it, thanks for bringing it up.

**Comment by billymeinke** [comment]
Hey @parkjc did you get a chance to look at this? Thought you mentioned it was bringing code back from the old search function. Thanks!

**Comment by enriquezm** [comment]
@billymeinke yeah i was in the process of working on this last week and almost finished. I'll get @parkjc on board and add tags by today.
