### ISSUE TITLE
Add "Improve this page on Github" banner or button on tutorials

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#73]
Would be great to have a banner or button at the bottom of each tutorial that people can click to fork + edit the page on Github. I've seen it implemented elsewhere, let me know if I can find a code snippet for you @parkjc @enriquezm

**Comment by enriquezm** [comment]
@billymeinke I've also seen these buttons, but I think it's to fork the whole project yeah? Is that fine, or did you want something that only forks a specific page?

**Comment by billymeinke** [comment]
This is essentially what I'm looking for: http://ben.balter.com/2015/09/13/github-pages-edit-button/ /cc @fjumawan @parkjc

**Comment by parkjc** [comment]
@billymeinke @fjumawan added the button near the bottom of the page. should i make any changes?

**Comment by billymeinke** [comment]
This looks great, thanks @parkjc. Good for now.
