### ISSUE TITLE
Write up "Getting Started" section of README file

### ISSUE THREAD

**Issue by billymeinke** [uhm-coe/flow#78]
So others know where to start to run locally, etc etc etc.

**Comment by billymeinke** [comment]
This is looking good, @parkjc. We should add a section at the bottom that shows the project team and how to get in touch.

**Comment by parkjc** [comment]
@parkjc change full names to relative links. ask other project members for permission

**Comment by billymeinke** [comment]
Looks great, thanks @parkjc
