### ISSUE TITLE
Twitter post mentioning a blank Twitter handle.

### ISSUE THREAD

**Issue by ghost** [uhm-coe/flow#85]
When pressing Twitter share button, the tweet refers to a blank Twitter handle "@".
![screen shot 2016-04-15 at 12 53 14 pm](https://cloud.githubusercontent.com/assets/15221414/14576976/c154074e-0309-11e6-8b1b-c07caf256fc5.png)

**Comment by parkjc** [comment]
are twitter handles referenced by the account your logged into? or is it just manually typed it to refer to someone, for example hashtags (#fake)

**Comment by ghost** [comment]
I don't think it's referencing the account I logged into, it's more from COE or TDP if there is a Twitter account.

**Comment by parkjc** [comment]
shall we add a basic COE / TDP account?

**Comment by ghost** [comment]
Let's wait on @billymeinke when he gets back. I think when we create a COE/TDP Twitter account, or if there is already one, we need to make sure we monitor the account for all Twitter mentions on questions.

**Comment by billymeinke** [comment]
@fjumawan @parkjc I'm seeing connecting Assist to the COE social media accounts as an option. I don't think we need to spin up a new social media account for Assist, but it'd be great to be able to automate sharing out tweets when new tutorials are posted, and when people want to interact with a social media account regarding Assist

**Comment by billymeinke** [comment]
@kccoburn This is the issue I'd like your thoughts on. We're making it easy for people to share the tutorials over social media, but we don't have unique social media accounts on each network for assist. Is there a way we can mention the COE Twitter account so that folks can be driven back to the COE website?

**Comment by kccoburn** [comment]
Can you give me an example of how a post might appear on Twitter (the
content)? I'm not sure I'm following you.

On Fri, Apr 22, 2016 at 3:33 PM, Billy Meinke notifications@github.com
wrote:

> @kccoburn https://github.com/kccoburn This is the issue I'd like your
> thoughts on. We're making it easy for people to share the tutorials over
> social media, but we don't have unique social media accounts on each
> network for assist. Is there a way we can mention the COE Twitter account
> so that folks can be driven back to the COE website?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/assist/issues/85#issuecomment-213644394

## 

KC Coburn
Academic Support
Continuing Education Specialist
UH Manoa College of Education

http://www.facebook.com/uhcoe  https://twitter.com/#!/uh_coe
http://www.pinterest.com/uhcoe/
http://www.youtube.com/user/UHCollegeofEducation/featured
https://plus.google.com/u/0/+UHManoaCoe/posts
kcoburn@hawaii.edu
(808) 956-6320
https://kccoburn.wordpress.com/

**Comment by billymeinke** [comment]
@kccoburn When a user clicks on the Twitter icon to share a tutorial, they are given a pre-formatted tweet like this:

![screen shot 2016-04-26 at 12 29 27 pm](https://cloud.githubusercontent.com/assets/3204193/14836286/aa653dce-0baa-11e6-8d09-a909c201adf3.png)

We have some control over what the tweet is formatted like, and I think it'd be smart to mention the @UH_COE account to direct people back to our web presence. Do you have ideas about how this could be done?

**Comment by billymeinke** [comment]
@kccoburn Any last thoughts before we close? Thanks!

**Comment by kccoburn** [comment]
All I can think of is creating a separate account that is for internal (but
ok for public to see?) information. Texas A&M publishes a blog post for
their internal fac/staff; it can be viewed by the public, but is of little
interest. It's for this exact issue; updating facstaff of IT and support
issues, tips. Posts are short and sweet, like these tweets.

I'm happy to create a Twitter feed just for this purpose, if you like? I
can call it something like COE_facstaff and we can promote it internally? I
don't know how many faculty use Twitter, which is why I'm suggesting a blog
RSS feed that maybe publishes to the COE-L?

On Fri, Apr 29, 2016 at 11:12 AM, Billy Meinke notifications@github.com
wrote:

> @kccoburn https://github.com/kccoburn Any last thoughts before we
> close? Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/assist/issues/85#issuecomment-215883194

## 

KC Coburn
Academic Support
Continuing Education Specialist
UH Manoa College of Education

http://www.facebook.com/uhcoe  https://twitter.com/#!/uh_coe
http://www.pinterest.com/uhcoe/
http://www.youtube.com/user/UHCollegeofEducation/featured
https://plus.google.com/u/0/+UHManoaCoe/posts
kcoburn@hawaii.edu
(808) 956-6320
https://kccoburn.wordpress.com/

**Comment by billymeinke** [comment]
Thanks @kccoburn! I'd rather not create more accounts that would need to be managed at this time :)

@parkjc Go ahead and edit the auto-formatted tweet to not mention a Twitter account. Can the tweet say something to the effect of "A tutorial on Assist: {name of tutorial}{link}"?

We can revisit this when we think it'll be useful for COE folks to have a distinct online presence for Assist.

**Comment by kccoburn** [comment]
Hey! This may not apply here, but you know that the intranet posts updates
on the homepage every time they are made. Could some form of what you are
contemplating go in the space to the left, just above my Social Web
content?

[image: Inline image 1]

On Mon, May 2, 2016 at 12:18 PM, Billy Meinke notifications@github.com
wrote:

> Thanks @kccoburn https://github.com/kccoburn! I'd rather not create
> more accounts that would need to be managed at this time :)
> 
> @parkjc https://github.com/parkjc Go ahead and edit the auto-formatted
> tweet to not mention a Twitter account. Can the tweet say something to the
> effect of "A tutorial on Assist: {name of tutorial}{link}"?
> 
> We can revisit this when we think it'll be useful for COE folks to have a
> distinct online presence for Assist.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/assist/issues/85#issuecomment-216382341

## 

KC Coburn
Academic Support
Continuing Education Specialist
UH Manoa College of Education

http://www.facebook.com/uhcoe  https://twitter.com/#!/uh_coe
http://www.pinterest.com/uhcoe/
http://www.youtube.com/user/UHCollegeofEducation/featured
https://plus.google.com/u/0/+UHManoaCoe/posts
kcoburn@hawaii.edu
(808) 956-6320
https://kccoburn.wordpress.com/

**Comment by billymeinke** [comment]
Hey @kccoburn can you include another screen shot of what you mean? This may be a good fit, but your image isn't working :(

**Comment by kccoburn** [comment]
Try looking at the link here? it's in the center column, headed: "RECENT
INTRANET EDITS."  https://coe.hawaii.edu/intranet

On Fri, May 20, 2016 at 10:59 AM, Billy Meinke notifications@github.com
wrote:

> Hey @kccoburn https://github.com/kccoburn can you include another
> screen shot of what you mean? This may be a good fit, but your image isn't
> working :(
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/assist/issues/85#issuecomment-220717055

## 

KC Coburn
Academic Support
Continuing Education Specialist
UH Manoa College of Education

http://www.facebook.com/uhcoe  https://twitter.com/#!/uh_coe
http://www.pinterest.com/uhcoe/
http://www.youtube.com/user/UHCollegeofEducation/featured
https://plus.google.com/u/0/+UHManoaCoe/posts
kcoburn@hawaii.edu
(808) 956-6320
https://kccoburn.wordpress.com/

**Comment by billymeinke** [comment]
@kccoburn Hmm...I don't know if this is a good fit. Let's hold off on connecting Assist to the COE social media accounts for the time being. Thanks!

**Comment by kccoburn** [comment]
Oh, no, I was meaning that as an alternative to COE social media accounts.
I don't think there's a good fit there. But what Paul did, by publishing a
sort of RSS on the Intranet home page, was provide updates to people on
what's new, what's changed within the Intranet. I was suggesting that you
have some similar type of RSS available to facstaff for Assist updates? We
could get rid of my SM information and put an RSS for assist where it is on
the page I sent you.

On Mon, May 23, 2016 at 11:43 AM, Billy Meinke notifications@github.com
wrote:

> @kccoburn https://github.com/kccoburn Hmm...I don't know if this is a
> good fit. Let's hold off on connecting Assist to the COE social media
> accounts for the time being. Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/uhm-coe/assist/issues/85#issuecomment-221105323

## 

KC Coburn
Academic Support
Continuing Education Specialist
UH Manoa College of Education

http://www.facebook.com/uhcoe  https://twitter.com/#!/uh_coe
http://www.pinterest.com/uhcoe/
http://www.youtube.com/user/UHCollegeofEducation/featured
https://plus.google.com/u/0/+UHManoaCoe/posts
kcoburn@hawaii.edu
(808) 956-6320
https://kccoburn.wordpress.com/
