### ISSUE TITLE
Add unordered list for markdown

### ISSUE THREAD

**Issue by ghost** [uhm-coe/flow#87]
I checked Myles' documentation on the markdown and he only emphasized ordered list. Can the unordered list be activated via markdown?

**Comment by parkjc** [comment]
@fjumawan just checked, its because custom unordered list wasn't written, just ordered lists. Do you want me to add it? if so, is there a specific design in how you want them to be portrayed? (default is the black dot)

**Comment by ghost** [comment]
@parkjc Let's go with the black dot.
