### ISSUE TITLE
Remove extra space and line after each bullet point items

### ISSUE THREAD

**Issue by ghost** [uhm-coe/flow#88]
![screen shot 2016-04-21 at 11 12 25 am](https://cloud.githubusercontent.com/assets/15221414/14724476/1f2fad80-07b2-11e6-8acd-06482667b54b.png)

**Comment by billymeinke** [comment]
@fjumawan have you peeked at which CSS class is being used for these tall bulleted lists? The default style (unordered list) may have been changed instead of creating a new class for this taller list type. I don't see it in use much throughout the site.

**Comment by ghost** [comment]
@billymeinke Will look into this
