### ISSUE TITLE
Reduce Spacing Between  and Slightly Indent Unordered List Item

### ISSUE THREAD

**Issue by ghost** [uhm-coe/flow#94]
![screen shot 2016-05-10 at 9 12 15 am](https://cloud.githubusercontent.com/assets/15221414/15159304/c749976a-168f-11e6-8871-15b5d8d54125.png)

**Comment by parkjc** [comment]
Would we be able to do an alternative? Use main unordered list as a header and the nested list as the unordered list

**Comment by ghost** [comment]
@parkjc @billymeinke This is what I get when I use Header 5 ##### and and Header 6 ###### respectively

![screen shot 2016-05-23 at 12 23 37 pm](https://cloud.githubusercontent.com/assets/15221414/15486423/4c6d3130-20e1-11e6-8f61-a9b5bfed0e4f.png)

**Comment by ghost** [comment]
@parkjc @billymeinke Sorry, misinterpreted that... used Header 4 and nested an unordered list under one of the Header 4 points
![screen shot 2016-05-23 at 12 37 39 pm](https://cloud.githubusercontent.com/assets/15221414/15486696/4528f6aa-20e3-11e6-9d78-f40db01c5331.png)

**Comment by billymeinke** [comment]
This looks better, thanks @fjumawan. We'll just need to be careful about line spacing between the paragraph above and the beginning of the lists.
